In [2]:
import numpy as np
x = np.arange(1, 10).reshape(3, 3)

x
print(x)
for i in range(3):
    for j in range(3):
        if (i <3 and j ==2 ):
            print(x[i][j],end=" ")
print("")           
for i in range(3):
    for j in range(3):
        if (i <3 and j ==1 ):
            print(x[i][j],end=" ")
print("")            
for i in range(3):
    for j in range(3):
        if (i <3 and j ==0 ):
            print(x[i][j],end=" ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 6 9 
2 5 8 
1 4 7 

In [4]:
def find_indices(arr, target):
    indices = [index for index, value in enumerate(arr) if value == target]
    return indices

input_array = [4, 2, 7, 8, 2, 9, 2, 4]
target_number = 2

result_indices = find_indices(input_array, target_number)
if result_indices:
    print(f"The target number {target_number} appears at indices: {result_indices}")
else:
    print(f"The target number {target_number} is not present in the array.")

The target number 2 appears at indices: [1, 4, 6]
